In [22]:
import numpy as np

In [ ]:
##lets see 1d array 

In [18]:
print("1d array is :",array)

1d array is : [[1 2 3]
 [4 5 6]]


In [23]:
##now lets dive into 2d array

In [16]:
array = np.array([[1,2,3],
                  [4,5,6]])

In [25]:
print("2d_array is :",array)

2d_array is : [[1 2 3]
 [4 5 6]]


In [28]:
### lets see nthe difference between list and numpy array
##list

In [41]:
list = [1,2,3,4,5]
print([i*2 for i in list])

[2, 4, 6, 8, 10]


In [42]:
##array in numpy

In [44]:
arr= np.array([1,2,3,4,5])
print(arr*2)

[ 2  4  6  8 10]


In [45]:
##lets see how much time difference is there in numpy array and list execution 

In [48]:
import time 

In [59]:
l = [i for i in range(10000000)]
start_time = time.time()
squaring_each = [i*2 for i in l]
time_pylist = time.time() - start_time
print(time_pylist)

0.671454906463623


In [61]:
l = np.arange(10000000)
start_time = time.time()
squaring_each = l*2
time_pylist = time.time() - start_time
print(time_pylist)

0.015511512756347656


In [64]:
#from above output its clear numpy makes things so much faster and easier 

### lets get to know about differenet ways to make constant values array in numpy

In [67]:
zero_array = np.zeros((2,3))
print("zeros array :", zero_array)

zeros array : [[0. 0. 0.]
 [0. 0. 0.]]


In [69]:
ones_array = np.ones((2,3))
print("ones array is :", ones_array)

ones array is : [[1. 1. 1.]
 [1. 1. 1.]]


In [73]:
constant_array = np.full((3,3),6)
print(constant_array)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
##random generates random number of given order matrix 

In [77]:
import random
random_noarray = np.random.random((2,2))
print(random_noarray)

[[0.94089102 0.5080077 ]
 [0.4233695  0.34888833]]


In [82]:
###arange 

In [85]:
arange_sequence = np.arange(1,10,1)
print(arange_sequence)

[1 2 3 4 5 6 7 8 9]
