In [2]:
import numpy as np

In [22]:
### VECTOR , MATRIX , TENSOR

In [23]:
vector = [1,2,3,4]
print("vector: ",vector)

vector:  [1, 2, 3, 4]


In [24]:
matrix = [[1,2,3],[4,5,6]]
print("matrix: ",matrix)

matrix:  [[1, 2, 3], [4, 5, 6]]


In [25]:
tensor = [[[1,2,3],[4,5,6]], ##this is first matrix with 2 rows 3 colums
         [[7,8,9],[10,11,12]]] ##second matrix with 2 rows 3 colums
##whenever this matrix gets stacked up that gives more than 2 dimensions
print(tensor)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]


In [26]:
## array properties

In [34]:
#shape gives number of rows and columns
array = np.array([[1,2,3,4],
                  [2,3,4,5]])
print(array.shape)

(2, 4)


In [39]:
#dimension :=> it gives dimension of the array
a = np.array([[1,2,3],[1,1,1]])
tensor = np.array([[[1,2,3],[4,5,6]], ##this is first matrix with 2 rows 3 colums
         [[7,8,9],[10,11,12]]])
print(tensor.ndim)
print(a.ndim)

3
2


In [44]:
#size :-> it gives number of data in an array 
a = np.zeros((2,3))
print(a)
print(a.size)

[[0. 0. 0.]
 [0. 0. 0.]]
6


In [45]:
#datatype /dtype => gives the data type of the list 
l = np.array([[[1,2,3],[4,5,6]], ##this is first matrix with 2 rows 3 colums
         [[7,8,9],[10,11,12]]])
print(l.dtype)

int32


In [3]:

##ARRAY RESHaping
l = np.arange(12)
reshaped = l.reshape((4,3))
print(reshaped)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
