**array creation from other python methods

In [10]:
import numpy as np 

In [24]:
list1 = np.array([[1,2,3,4,5],
                 [12,34,45,6,7]])
print(list1)

[[ 1  2  3  4  5]
 [12 34 45  6  7]]


In [16]:
list.size

10

In [25]:
b = list1.reshape(5,2)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5 12]
 [34 45]
 [ 6  7]]


In [27]:
##instrinsic array creation thorugh built-in objects

In [30]:
array = np.arange(1,10,2)
print(array)

[1 3 5 7 9]


In [32]:
array2 = np.ones((2,2))
print(array2)

[[1. 1.]
 [1. 1.]]


In [35]:
array3 = np.zeros((5,5))
print(array3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
array4 = np.full((3,3),7)
print(array4)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [40]:
array5 = np.linspace(1,5,4)
print("this prints values from 1 to 5 with equal spacing of 4 : ",array5)

this prints values from 1 to 5 with equal spacing of 4 :  [1.         2.33333333 3.66666667 5.        ]


In [48]:
identity_matrix = np.identity(2)
print(identity_matrix)
print(identity_matrix.shape)

[[1. 0.]
 [0. 1.]]
(2, 2)


In [54]:
## we can reshape and undo the reshaping of that array 
a = np.arange(50)
print(a)
reshape = a.reshape(2,25)
print(reshape)
undo = reshape.ravel()
print(undo)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [60]:
## we can apply operations rowwise or columnwise
x = np.array([[1,2,3],
             [4,5,6]])
print(x.sum(axis = 0)) #3this is column wise 4+1 2+5 3+6

print(x.sum(axis = 1))

[5 7 9]
[ 6 15]


In [63]:
print(x.T) # T is transpose that converts row into column and column into row 

[[1 4]
 [2 5]
 [3 6]]


In [68]:
for i in x:
    print(i)

for i in x.flat:
    print(i)


[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [72]:
print(x.ndim)
print(x.size)
print(x.shape)

2
6
(2, 3)


In [74]:
#we can also know how much memory an array holds
print(x.nbytes)

24


In [78]:
l = np.array([1,2,3,5,6])
print(l.argmax()) #max value index
print(l.argmin()) #min value index

4
0


In [86]:
y = np.random.random((2,3))
print(y)
y.sort()
print(y)

[[0.17529903 0.45651453 0.41844959]
 [0.58467082 0.24285724 0.07940632]]
[[0.17529903 0.41844959 0.45651453]
 [0.07940632 0.24285724 0.58467082]]


In [97]:
z = np.random.random(4)
print(z)

print(z.argsort())


[0.41773934 0.14758302 0.01642634 0.83868783]
[2 1 0 3]


In [99]:
##we can sort find max min using the arg and axis 
l = np.random.random((2,2))
print(l)
print(l.argsort(axis = 1))
print(l.argmax(axis = 0))

[[0.6547933  0.57417284]
 [0.4047227  0.97463301]]
[[1 0]
 [0 1]]
[0 1]
