In [2]:
#mathematical operations in numpy that can be done in simplest way unlike list operations in python

In [6]:
import numpy as np 

In [10]:
arr1 = np.array ([[1,2],
                [3,4]])
arr2 = np.array([[1,1],
                 [1,1]])

print(arr1+arr2)
print(arr1 *arr2)

[[2 3]
 [4 5]]
[[1 2]
 [3 4]]


In [14]:
square_root = np.sqrt(arr1)
print(square_root)

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [16]:
print(arr1.min())
print(arr1.max())

1
4


In [17]:
print(arr1)


[[1 2]
 [3 4]]


In [21]:
print(type(np.where(arr1>=2)))

<class 'tuple'>


In [24]:
print((np.where(arr1>=2)))

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))


In [27]:
ar = np.array([[1,2,3],
              [2,3,4]])
print(np.count_nonzero(ar))
print(np.nonzero(ar))

6
(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))
